# Generated by Django 4.1.2 on 2022-10-24 17:02

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(default='hotels/default.jpg', upload_to=backend.models.upload_to, verbose_name='Image')),
                ('address', models.TextField(null=True)),
                ('services', models.TextField(null=True)),
                ('rating', models.TextField(null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(default='rooms/default.jpg', upload_to=backend.models.upload_to_1, verbose_name='Image')),
                ('type', models.CharField(choices=[('president', 'president'), ('family', 'family'), ('double', 'double'), ('single', 'single')], max_length=50)),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('pets', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('description', models.TextField(null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='backend.hotel')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=0)),
                ('check_in', models.DateTimeField(null=True, verbose_name='check in date')),
                ('check_out', models.DateTimeField(null=True, verbose_name='check out field')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.hotel')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.room')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
